# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

variables:
- group: 'project-flash-cache'

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: NodeTool@0
  inputs:
    versionSource: 'spec'
    versionSpec: '16.x'
    checkLatest: true

- script: |
    node -v
  displayName: 'Get node version'

- script: |
    npm -v
  displayName: 'Get npm version'

- task: Bash@3
  displayName: 'Install dependencies on CDK project'
  inputs:
    targetType: 'inline'
    script: |
      # install dependencies
      
      npm install
    workingDirectory: 'infrastructure'

- task: Bash@3
  displayName: 'Install dependencies on app'
  inputs:
    targetType: 'inline'
    script: |
      # install dependencies
      
      npm install
    workingDirectory: 'app'

- task: AWSCLI@1
  inputs:
    awsCredentials: 'AWS Sysadmin CANVIA cp-cramirez'
    regionName: 'us-east-1'
    awsCommand: 'aws sts get-caller-identity'

- task: Bash@3
  displayName: 'Synthesize CDK app'
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here
      
      npx cdk synth
    workingDirectory: 'infrastructure'
